/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import utilidades.BaseDeDatos;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;
import javax.swing.JPanel;

/**
 *
 * @author Santiago
 */
public final class FramePrincipal extends javax.swing.JFrame {

    private LoginPanel loginPanel;
    private MenuPanel menuPanel;
    BaseDeDatos baseDeDatos;

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        generarDiseños();
        baseDeDatos = new BaseDeDatos();
    }

    public void generarDiseños() {

        //Instalar fuente personalizada
        try {
            Font font = Font.createFont(Font.TRUETYPE_FONT,
                    new File("./program/Chocolada.ttf"));
            loginPanel = new LoginPanel(font, this.barraProgreso, this);
            menuPanel = new MenuPanel(font, this.barraProgreso, this);
            changePanel(loginPanel);

            //panelPrincipal.add(new menuPanel(font,this.barraProgreso));
        } catch (FontFormatException | IOException e) {
            e.printStackTrace();
        }
        barraProgreso.setVisible(false);

    }

    public void changePanel(JPanel panel) {
        panelPrincipal.removeAll();
        panelPrincipal.add(panel);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();

    }
    public static final byte LOGIN_PANEL = 0;
    public static final byte MENU_PANEL = 1;

    public void cambiarMenu(int i) {
        switch (i) {
            case LOGIN_PANEL:
                changePanel(loginPanel);
                return;
            case MENU_PANEL:
                changePanel(menuPanel);
                return;
            default:
                changePanel(loginPanel);
                return;
        }
    }

    public MenuPanel getMenuPanel() {
        return menuPanel;
    }

    public LoginPanel getLoginPanel() {
        return loginPanel;
    }

    public BaseDeDatos getBaseDeDatos() {
        return baseDeDatos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        barraProgreso = new javax.swing.JProgressBar();
        panelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        barraProgreso.setForeground(new java.awt.Color(255, 102, 102));
        jPanel3.add(barraProgreso, java.awt.BorderLayout.PAGE_END);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new java.awt.BorderLayout());
        jPanel3.add(panelPrincipal, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgreso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
